language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=catfs=debug,integration_tests=debug
  matrix:
    - CATFS_SELF_HOST=0
    - CATFS_SELF_HOST=1
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfuse-dev apport
  # from https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/plain/README
  - sudo apt-get install xfslibs-dev uuid-dev e2fsprogs automake gcc libuuid1 quota attr libattr1-dev make libacl1-dev libaio-dev xfsprogs libgdbm-dev gawk fio dbench uuid-runtime
  - git clone https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/ && cd xfstests-dev && make && sudo make install
  - sudo useradd fsgqa
  - sudo useradd 123456-fsgqa
  
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_cache:
  - rm -Rf target/test/
  - export PATH=$PATH:/var/lib/xfstests/ltp
script:
  - (cargo test large_dir && cargo test) || (if [ -e core* ]; then gdb --batch --ex "thread apply all bt" $(file core* | cut -d\' -f 2) core*; fi; false)
