language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=catfs=debug,integration_tests=debug
  matrix:
    - CATFS_SELF_HOST=0
    - CATFS_SELF_HOST=1
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfuse-dev apport
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_cache:
  - rm -Rf target/test/
script:
  - cargo test || if [ -e core* ]; then gdb --batch --ex "thread apply all bt" $(file core* | cut -d\' -f 2) core*; fi
