language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=catfs=debug,fuse=debug,integration_tests=debug
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libfuse-dev
matrix:
  allow_failures:
    - rust: nightly
