[package]
name = "catfs"
version = "0.1.0"
authors = ["Ka-Hing Cheung <khc@hxbc.us>"]
description = "Cache AnyThing filesystem"
keywords = ["filesystem", "fuse", "cache"]
categories = ["caching", "filesystem"]

[dependencies]
backtrace = "0.3"
fuse = "0.3.0"
log = "0.3"
env_logger = "0.4"
clap = "2.25.0"
time = "0.1"
libc = "0.2"
chan-signal = "0.2"
xattr = "0.2"
threadpool = "1.4"
itertools = "0.6"
rand = "0.3"

[lib]
test = false
