[package]
name = "catfs"
version = "0.1.0"
authors = ["Ka-Hing Cheung <khc@hxbc.us>"]

[dependencies]
fuse = "0.3.0"
log = "0.3"
env_logger = "0.3"
clap = "2.25.0"
time = "0.1"
libc = "0.2"
chan-signal = "0.2"
